package com.jobseekerorganizer.accountms.web.model;

import java.time.OffsetDateTime;
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.jobseekerorganizer.accountms.domain.ProfileImage;
import com.jobseekerorganizer.accountms.domain.UserAccount;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UserAccountDTO {

	private String id;
	private String fName;
	private String lName;
	private String email;
	private String password;
	private ProfileImage profileImage;
	private OffsetDateTime createdAt;
	private OffsetDateTime lastModifiedDate;
		


}
