package com.jobseekerorganizer.accountms.web.model;


import java.time.OffsetDateTime;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;


@DynamoDBTable(tableName = "UserAccount")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
public class UserAccount {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute(attributeName = "fName")
	private String fName;

	@DynamoDBAttribute(attributeName = "lName")
	private String lName;

	@DynamoDBAttribute(attributeName = "email")
	private String email;

	@DynamoDBAttribute(attributeName = "password")
	private String password;
//	
//	@DynamoDBAttribute
//	private ProfileImage profileImage;
	
	@DynamoDBAttribute(attributeName = "createdDate")
	private OffsetDateTime createdAt;
	
	@DynamoDBAttribute(attributeName = "lastModifiedDate")
	private OffsetDateTime lastModifiedDate;
		
}
