package com.jobseekerorganizer.accountms.web.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.jobseekerorganizer.accountms.ProfileImage;
import com.jobseekerorganizer.accountms.web.model.UserAccount;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UserAccountDTO {

	private String id;
	private String fName;
	private String lName;
	private String email;
	private String password;
	private ProfileImage profileImage;
	
	public UserAccount toUserAccount() {
		return UserAccount.builder()
				.email(this.getEmail())
				.fName(this.getFName())
				.lName(this.getLName())
				.password(this.getPassword()).build();
	}

}
